// <auto-generated />
using IGraficasIES;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Practica9.Migrations
{
    [DbContext(typeof(MiContexto))]
    [Migration("20231127190636_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IGraficasIES.ProfesorExtendido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCivilProfesor")
                        .HasColumnType("int");

                    b.Property<int>("Estatura")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("ProfesorFuncionarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorFuncionarioId")
                        .IsUnique()
                        .HasFilter("[ProfesorFuncionarioId] IS NOT NULL");

                    b.ToTable("ProfesorExtendido");
                });

            modelBuilder.Entity("IGraficasIES.ProfesorFuncionario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyoIngresoCuerpo")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DestinoDefinitivo")
                        .HasColumnType("bit");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("EsFuncionario")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeguroMedico")
                        .HasColumnType("int");

                    b.Property<int>("TipoProfesor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProfesorFuncionario");
                });

            modelBuilder.Entity("IGraficasIES.ProfesorExtendido", b =>
                {
                    b.HasOne("IGraficasIES.ProfesorFuncionario", null)
                        .WithOne("ProfesorExtendido")
                        .HasForeignKey("IGraficasIES.ProfesorExtendido", "ProfesorFuncionarioId");
                });

            modelBuilder.Entity("IGraficasIES.ProfesorFuncionario", b =>
                {
                    b.Navigation("ProfesorExtendido");
                });
#pragma warning restore 612, 618
        }
    }
}
